---
- name: install apt packages
  apt:
    name: '{{item}}'
  loop:
    - zfs-dkms
    - zfsutils-linux

- name: get ZFS info
  zfs_facts:
    name: '{{zpool_name}}'
    recurse: yes

- name: create dataset
  zfs:
    name: '{{item.name}}'
    state: present
    extra_zfs_properties: '{{item.properties}}'
  loop: '{{zfs_datasets}}'
  when: item.name not in (ansible_zfs_datasets | map(attribute='name'))

- name: create directories
  file:
    path: '/{{item.0.name}}/{{item.1}}'
    state: directory
  with_subelements:
    - '{{zfs_datasets}}'
    - directories

- name: install systemd files
  template:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
  loop:
    - zfs-snapshot.service
    - zfs-snapshot.timer
  notify: reload systemd

- name: enable timers
  service:
    name: '{{ item }}'
    state: 'started'
    enabled: 'yes'
  loop:
    - zfs-snapshot.timer
