---
- hosts: ap-forum
  vars_files:
    - secrets.yml
  vars:
    discourse:
      -
        name: atom-china
        domain: atom-china.org
        smtp_user: '{{ ses_smtp_user_atom_china }}'
        smtp_password: '{{ ses_smtp_secret_atom_china }}'
    letsencrypt:
      - atom-china.org
  roles:
    - common
    - discourse
    - docker
    - letsencrypt
    - nginx
