---
- hosts: ap-home
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - jybox.net
    # rsync_users:
    #   -
    #     username: 'synology'
    #     password: '{{ rsync_synology_password }}'
  roles:
    - common
    - nginx
    - letsencrypt
    # - rsync
    - frps
