---
# No longer supported since ansible 2.17
# /opt/homebrew/opt/ansible@9/bin/ansible-playbook
# - hosts: voyager
#   vars:
#     nextdata_exposed: true
#     # dns_proxied: true
#     frp_client_proxies:
#       - name: wireguard
#         local_port: 41194
#         remote_port: 41194
#         type: udp
#   vars_files:
#     - secrets.yml
#     - voyager-secrets.yml
#   roles:
#     - common
#     - pppoe
#     - router
#     - clash-redir
#     - dnsmasq
#     - netdata
#     - wireguard
#     - frpc

- hosts: infinity
  vars_files:
    - secrets.yml
    - infinity-secrets.yml
  vars:
    nextdata_exposed: true
    letsencrypt:
      - 'nextcloud.{{ infinity_domain }}'
      - 'miniflux.{{ infinity_domain }}'
      - 'bitwarden.{{ infinity_domain }}'
      - 'lobechat.{{ infinity_domain }}'
      - 'home.{{ infinity_domain }}'
    miniflux_base_url: 'https://miniflux.{{ infinity_domain }}/'
    bitwarden_base_url: 'https://bitwarden.{{ infinity_domain }}/'
    zpool_name: storage
    frp_client_proxies:
      - name: nginx-http
        local_port: 80
        remote_port: 80
        type: tcp
      - name: nginx-https
        local_port: 443
        remote_port: 443
        type: tcp
      - name: wireguard-default
        local_port: 10011
        local_ip: 10.0.0.1
        remote_port: 10011
        type: udp
      - name: wireguard-mexin
        local_port: 10331
        local_ip: 10.0.0.1
        remote_port: 10331
        type: udp
    restic_backup_paths:
      - /storage/db
      - /storage/nextcloud
      - /storage/private
      - /storage/shares/AudioWorks/Caipai
      - /storage/shares/VideoWorks/Rendered
  roles:
    - bitwarden
    - common
    - docker
    - frpc
    - letsencrypt
    - lobechat
    - netdata
    - nextcloud
    - nginx
    - restic
    - samba
    - transmission
    - zfs

- hosts: refinity
  vars_files:
    - secrets.yml
  roles:
    - common
    - frps

- hosts: satellite-sin
  vars_files:
    - secrets.yml
  roles:
    - common
    - frps
