---
- hosts: ap-home
  vars_files:
    - secrets.yml
  vars:
    letsencrypt:
      - jybox.net
    # rsync_users:
    #   -
    #     username: 'synology'
    #     password: '{{ rsync_synology_password }}'
  pre_tasks:
    - include_tasks: tasks/common-packages.yml
  roles:
    - nginx
    - letsencrypt
    # - rsync
    - frps
