---
- hosts: nomad
  vars_files:
    - secrets.yml
  vars:
    swap_size: 512M
  pre_tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/common-packages.yml
    - include_tasks: tasks/swap.yml
    - include_tasks: tasks/shell-config.yml
  roles:
    - { role: docker, tags: docker }
    - { role: nomad, tags: nomad }
  tasks:
    - include_tasks: tasks/local-hosts.yml

- hosts: sgp-nomad-core1
  tags: traefik
  vars:
    nomad_run_jobs:
      - nomad-jobs/traefik.hcl
  pre_tasks:
    - name: set internal CA certificate in nomad variables
      command: nomad var put -in json -force traefik-internal-certs -
      args:
        stdin: "{{ {'Items': {'CA_PEM': lookup('file', 'internal-certs/ca.pem')}} | to_json }}"
      changed_when: false
  roles:
    - nomad-jobs

- hosts: sgp-nomad-core1
  tags: postgresql
  vars_files:
    - secrets.yml
  vars:
    nomad_run_jobs:
      - nomad-jobs/postgresql.hcl
      - nomad-jobs/postgresql-backup.hcl
  pre_tasks:
    - name: create postgresql directories
      file:
        path: /var/lib/postgresql/data
        state: directory
        mode: '0755'

    - name: set postgresql password in nomad variables
      command: >-
        nomad var put -force
        postgresql-secrets
        POSTGRES_PASSWORD={{ postgres_superuser_password }}
      changed_when: false
  roles:
    - nomad-jobs
  post_tasks:
    - include_tasks: tasks/postgresql-auth.yml

- hosts: sgp-nomad-core1
  tags: garage
  vars_files:
    - secrets.yml
  vars:
    garage_apps:
      - {bucket: docker-registry, key: docker-registry, nomad_var: garage-auth/registry}
    nomad_run_jobs:
      - nomad-jobs/garage.hcl
  pre_tasks:
    - name: create garage data directory
      file:
        path: /var/lib/garage
        state: directory
        mode: '0755'

    - name: set garage rpc secret in nomad variables
      command: >-
        nomad var put -force
        garage-secrets
        RPC_SECRET={{ garage_rpc_secret }}
      changed_when: false
  roles:
    - nomad-jobs
  post_tasks:
    - include_tasks: tasks/garage-auth.yml

- hosts: sgp-nomad-core1
  tags: registry
  vars:
    nomad_run_jobs:
      - nomad-jobs/registry.hcl
  roles:
    - nomad-jobs

- hosts: sgp-nomad-core1
  tags: github-runner
  vars_files:
    - secrets.yml
  vars:
    nomad_run_jobs:
      - nomad-jobs/github-runner.hcl
      - nomad-jobs/github-runner-dispatcher.hcl
  pre_tasks:
    - name: set github runner secrets in nomad variables
      command: >-
        nomad var put -force
        github-runner-secrets
        GITHUB_PAT={{ github_pat }}
        WEBHOOK_SECRET={{ github_webhook_secret }}
      changed_when: false
  roles:
    - nomad-jobs
