---
- hosts: nomad
  vars_files:
    - secrets.yml
  pre_tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/common-packages.yml
    - include_tasks: tasks/shell-config.yml
  roles:
    - docker
    - nomad
  tasks:
    - include_tasks: tasks/local-hosts.yml
