---
clash_release: '1.1.0'
clash_redir_port: '7892'
lan_gateway_cidr: '10.0.0.1/24'
http_proxy_port: '8118'
clash_proxy_ports: [12345]
clash_dashbiard_secret: ''
clash_ignored_lan_ip: []
dns_proxied: false

clash_proxies: |
  proxies:
    - { name: 'Proxy', type: 'ss', server: '1.2.3.4', port: 12345, cipher: 'aes-128-gcm',password :'123456' }

  proxy-groups:
    - { name: 'Streaming', type: select, proxies: [Proxy] }
    - { name: 'Blocked', type: select, proxies: [REJECT] }

clash_rules: |
