version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.32.5
    container_name: bitwarden
    ports:
      - 8082:80
    environment:
      # - SIGNUPS_ALLOWED=true
      - DOMAIN={{ bitwarden_base_url }}
    volumes:
      - '{{ bitwarden_db }}:/data'
