---
- name: create bitwarden compose dir
  file:
    path: /root/bitwarden
    state: directory

- name: upload compose file
  template:
    src: 'docker-compose.yml'
    dest: '/root/bitwarden/docker-compose.yml'

- name: Start bitwarden
  command:
    cmd: docker compose up -d
    chdir: /root/bitwarden
  register: compose_upped
  changed_when: compose_upped.stderr is search('Creating|Starting|Recreated')
