version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - '{{ prometheus_root }}:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=100y'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    volumes:
      - '{{ grafana_root }}:/var/lib/grafana'

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - '{{ loki_root }}:/loki'
