---
- name: install apt packages
  apt:
    name: wireguard

- name: generate keys
  shell: umask 077; wg genkey | tee privatekey | wg pubkey > publickey
  args:
    chdir: /etc/wireguard
    creates: /etc/wireguard/privatekey

- name: load private key
  slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_private_key
  no_log: true

- name: fetch public key to controller
  fetch:
    src: /etc/wireguard/publickey
    dest: "{{ playbook_dir }}/wireguard-pubkeys/{{ inventory_hostname }}.pub"
    flat: true

- name: install wireguard configuration
  template:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  diff: false
  notify: restart wireguard
