---
- name: ensures directory exists
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '/root/downloads'
    - '/etc/frpc'

- name: download frp
  get_url:
    url: 'https://github.com/fatedier/frp/releases/download/v{{ frp_release }}/frp_{{ frp_release }}_linux_amd64.tar.gz'
    dest: '/root/downloads/frp.tar.gz'
  tags: [download]

- name: unarchive frp
  unarchive:
    src: '/root/downloads/frp.tar.gz'
    dest: '/root/downloads'
    remote_src: 'yes'

- name: install frpc
  copy:
    src: '/root/downloads/frp_{{ frp_release }}_linux_amd64/frpc'
    dest: /usr/bin/frpc
    remote_src: yes
    mode: '0755'

- name: generate frpc configure
  template:
    src: 'frpc.ini'
    dest: '/etc/frpc/frpc-{{ item }}.ini'
  with_items: '{{ frp_servers }}'
  register: generate_result

- name: create systemd service
  template:
    src: 'frpc.service'
    dest: '/etc/systemd/system/frpc@.service'
    mode: '0644'
  notify:
    - reload systemd

- name: restart frpc services
  service:
    name: 'frpc@{{ item }}'
    state: 'restarted'
    enabled: 'yes'
  with_items: '{{ frp_servers }}'
  when: generate_result.changed
